add description to Address
open-contracting-extensions/ocds_location_extension pull request #38
Opened 2023-08-28 14:11 UTC by odscjen

as needed for https://github.com/open-contracting/european-union-support/issues/160

2023-08-28 23:57 UTC, duncandewhurst requested changes

2023-08-28 23:57 UTC, duncandewhurst commented on release-schema.json
> +          "description": "A name or description of this address. This might include the name(s) of the address(s), or might provide a human-readable description of the address to be covered.",
Per the style guide

```suggestion
          "description": "The description of the address.",
```

2023-08-29 08:51 UTC, duncandewhurst approved these changes

2023-08-29 15:52 UTC, jpmckinney approved these changes

2023-08-29 15:52 UTC, merged